	nios_system u0 (
		.audio_BCLK                    (<connected-to-audio_BCLK>),                    //                    audio.BCLK
		.audio_DACDAT                  (<connected-to-audio_DACDAT>),                  //                         .DACDAT
		.audio_DACLRCK                 (<connected-to-audio_DACLRCK>),                 //                         .DACLRCK
		.audio_and_video_config_0_SDAT (<connected-to-audio_and_video_config_0_SDAT>), // audio_and_video_config_0.SDAT
		.audio_and_video_config_0_SCLK (<connected-to-audio_and_video_config_0_SCLK>), //                         .SCLK
		.audio_pll_clk_clk             (<connected-to-audio_pll_clk_clk>),             //            audio_pll_clk.clk
		.audio_pll_ref_reset_reset     (<connected-to-audio_pll_ref_reset_reset>),     //      audio_pll_ref_reset.reset
		.audio_pll_ref_clk_clk         (<connected-to-audio_pll_ref_clk_clk>),         //        audio_pll_ref_clk.clk
		.clk_clk                       (<connected-to-clk_clk>),                       //                      clk.clk
		.hex_0_export                  (<connected-to-hex_0_export>),                  //                    hex_0.export
		.hex_1_export                  (<connected-to-hex_1_export>),                  //                    hex_1.export
		.hex_2_export                  (<connected-to-hex_2_export>),                  //                    hex_2.export
		.hex_3_export                  (<connected-to-hex_3_export>),                  //                    hex_3.export
		.hex_4_export                  (<connected-to-hex_4_export>),                  //                    hex_4.export
		.hex_5_export                  (<connected-to-hex_5_export>),                  //                    hex_5.export
		.hex_6_export                  (<connected-to-hex_6_export>),                  //                    hex_6.export
		.hex_7_export                  (<connected-to-hex_7_export>),                  //                    hex_7.export
		.keys_export                   (<connected-to-keys_export>),                   //                     keys.export
		.ledg_export                   (<connected-to-ledg_export>),                   //                     ledg.export
		.ledr_export                   (<connected-to-ledr_export>),                   //                     ledr.export
		.ps2_0_CLK                     (<connected-to-ps2_0_CLK>),                     //                    ps2_0.CLK
		.ps2_0_DAT                     (<connected-to-ps2_0_DAT>),                     //                         .DAT
		.reset_reset_n                 (<connected-to-reset_reset_n>),                 //                    reset.reset_n
		.sdram_clk_clk                 (<connected-to-sdram_clk_clk>),                 //                sdram_clk.clk
		.sdram_wire_addr               (<connected-to-sdram_wire_addr>),               //               sdram_wire.addr
		.sdram_wire_ba                 (<connected-to-sdram_wire_ba>),                 //                         .ba
		.sdram_wire_cas_n              (<connected-to-sdram_wire_cas_n>),              //                         .cas_n
		.sdram_wire_cke                (<connected-to-sdram_wire_cke>),                //                         .cke
		.sdram_wire_cs_n               (<connected-to-sdram_wire_cs_n>),               //                         .cs_n
		.sdram_wire_dq                 (<connected-to-sdram_wire_dq>),                 //                         .dq
		.sdram_wire_dqm                (<connected-to-sdram_wire_dqm>),                //                         .dqm
		.sdram_wire_ras_n              (<connected-to-sdram_wire_ras_n>),              //                         .ras_n
		.sdram_wire_we_n               (<connected-to-sdram_wire_we_n>),               //                         .we_n
		.sram_DQ                       (<connected-to-sram_DQ>),                       //                     sram.DQ
		.sram_ADDR                     (<connected-to-sram_ADDR>),                     //                         .ADDR
		.sram_LB_N                     (<connected-to-sram_LB_N>),                     //                         .LB_N
		.sram_UB_N                     (<connected-to-sram_UB_N>),                     //                         .UB_N
		.sram_CE_N                     (<connected-to-sram_CE_N>),                     //                         .CE_N
		.sram_OE_N                     (<connected-to-sram_OE_N>),                     //                         .OE_N
		.sram_WE_N                     (<connected-to-sram_WE_N>),                     //                         .WE_N
		.switches_export               (<connected-to-switches_export>),               //                 switches.export
		.usb_0_INT1                    (<connected-to-usb_0_INT1>),                    //                    usb_0.INT1
		.usb_0_DATA                    (<connected-to-usb_0_DATA>),                    //                         .DATA
		.usb_0_RST_N                   (<connected-to-usb_0_RST_N>),                   //                         .RST_N
		.usb_0_ADDR                    (<connected-to-usb_0_ADDR>),                    //                         .ADDR
		.usb_0_CS_N                    (<connected-to-usb_0_CS_N>),                    //                         .CS_N
		.usb_0_RD_N                    (<connected-to-usb_0_RD_N>),                    //                         .RD_N
		.usb_0_WR_N                    (<connected-to-usb_0_WR_N>),                    //                         .WR_N
		.usb_0_INT0                    (<connected-to-usb_0_INT0>)                     //                         .INT0
	);

